apiVersion: v1
kind: Secret
metadata:
  name: converter-secret
stringData:
  PLACEHOLDER: "nothing"
  MONGO_PASS: "converterPassword"
  YT_API_KEY: "YOUR_KEY"
  SPOTIFY_CLIENT_ID: "YOUR_KEY"
  SPOTIFY_CLIENT_SECRET: "YOUR_KEY"
type: Opaque
